import { useMemo, useState } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { Link } from 'react-router-dom'
import { Reveal } from '../components/Reveal'
import { Eyebrow } from '../components/Eyebrow'
import { GradientText } from '../components/GradientText'
import { AnimatedCounter } from '../components/AnimatedCounter'
import { MagneticButton } from '../components/MagneticButton'
import { Seo } from '../components/Seo'
import {
  BUILD_LOG,
  GENERATED_AT,
  FIRST_COMMIT,
  TOTAL_COMMITS,
  ACTIVE_DAYS,
  NEW_COUNT,
  type BuildEntry,
  type BuildKind,
} from '../data/buildlog'

const EASE = [0.16, 1, 0.3, 1] as const

const REPO_URL = 'https://github.com/ArseniyCherednichenko/portfolio'

// The three honest buckets the generator sorts commits into, with the label
// and accent each gets on the page. "All" is the default, unfiltered view.
const FILTERS: ReadonlyArray<{ key: BuildKind | 'all'; label: string }> = [
  { key: 'all', label: 'Everything' },
  { key: 'new', label: 'Shipped' },
  { key: 'refine', label: 'Refined' },
  { key: 'docs', label: 'Documented' },
]

const KIND_META: Record<BuildKind, { label: string; dot: string; text: string }> = {
  new: { label: 'New', dot: 'bg-[#DCF87C]', text: 'text-[#DCF87C]' },
  refine: { label: 'Refined', dot: 'bg-sky-300/80', text: 'text-sky-300/80' },
  docs: { label: 'Notes', dot: 'bg-white/35', text: 'text-white/45' },
}

// Format an ISO date as "12 July 2026" (UTC-parsed so the day never drifts).
function formatDate(iso: string): string {
  const [y, m, d] = iso.split('-').map(Number)
  if (!y || !m || !d) return iso
  return new Intl.DateTimeFormat('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  }).format(new Date(Date.UTC(y, m - 1, d)))
}

// Shorter form for the day rail — "Sat 12 Jul".
function formatDay(iso: string): string {
  const [y, m, d] = iso.split('-').map(Number)
  if (!y || !m || !d) return iso
  return new Intl.DateTimeFormat('en-GB', {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
    timeZone: 'UTC',
  }).format(new Date(Date.UTC(y, m - 1, d)))
}

interface DayGroup {
  date: string
  entries: BuildEntry[]
}

// Collapse the flat, newest-first log into per-day groups (order preserved).
function groupByDay(entries: readonly BuildEntry[]): DayGroup[] {
  const groups: DayGroup[] = []
  for (const entry of entries) {
    const last = groups[groups.length - 1]
    if (last && last.date === entry.date) last.entries.push(entry)
    else groups.push({ date: entry.date, entries: [entry] })
  }
  return groups
}

function CommitRow({ entry, reduce }: { entry: BuildEntry; reduce: boolean | null }) {
  const meta = KIND_META[entry.kind]
  return (
    <motion.a
      layout={reduce ? false : 'position'}
      href={`${REPO_URL}/commit/${entry.hash}`}
      target="_blank"
      rel="noreferrer"
      initial={reduce ? false : { opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      exit={reduce ? undefined : { opacity: 0 }}
      transition={{ duration: 0.4, ease: EASE }}
      className="group/row relative flex items-start gap-3 rounded-xl px-3 py-3 transition-colors hover:bg-white/[0.03]"
    >
      <span className={`mt-[7px] h-1.5 w-1.5 shrink-0 rounded-full ${meta.dot}`} aria-hidden />
      <span className="min-w-0 flex-1">
        <span className="block leading-snug text-white/80 transition-colors group-hover/row:text-white">
          {entry.subject}
        </span>
        <span className="mt-1.5 flex items-center gap-2.5 text-xs">
          <span className={`font-semibold uppercase tracking-[0.16em] ${meta.text}`}>{meta.label}</span>
          <span aria-hidden className="text-white/15">
            ·
          </span>
          <span className="font-mono tabular-nums text-white/35 transition-colors group-hover/row:text-white/60">
            {entry.hash}
          </span>
        </span>
      </span>
      <span
        aria-hidden
        className="mt-0.5 shrink-0 text-white/20 transition-all duration-300 group-hover/row:translate-x-0.5 group-hover/row:text-white/50"
      >
        -&gt;
      </span>
    </motion.a>
  )
}

// /log — the build log. The Colophon says this site "gains one coherent
// improvement most days, so the commit history is part of the story"; this
// page is that story, read straight from the real git history (generated by
// scripts/generate-buildlog.mjs). No project takes centre stage here — the
// subject is the practice itself: showing up and shipping, in the open.
export default function BuildLog() {
  const reduce = useReducedMotion()
  const [active, setActive] = useState<BuildKind | 'all'>('all')

  const filtered = useMemo(
    () => (active === 'all' ? BUILD_LOG : BUILD_LOG.filter((e) => e.kind === active)),
    [active],
  )
  const groups = useMemo(() => groupByDay(filtered), [filtered])

  return (
    <>
      <Seo
        title="Build log"
        description="The real commit history of this site — every coherent improvement, straight from git. Built in the open by Arseniy Cherednichenko."
      />

      {/* HEADER */}
      <header className="mx-auto w-full max-w-3xl px-6 pb-10 pt-36 sm:pt-44">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, ease: EASE }}
        >
          <Eyebrow>Build log</Eyebrow>
        </motion.div>
        <motion.h1
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.05, ease: EASE }}
          className="mt-6 font-display text-5xl font-bold leading-[1.05] tracking-tight sm:text-7xl"
        >
          Built in the <GradientText>open.</GradientText>
        </motion.h1>
        <motion.p
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.15, ease: EASE }}
          className="mt-8 max-w-xl text-lg leading-relaxed text-white/60"
        >
          This site gains one coherent improvement most days. Here is the genuine record — every commit, read straight
          from git. Not a project, but the practice behind all of them: showing up and shipping something real.
        </motion.p>
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.7, delay: 0.25, ease: EASE }}
          className="mt-5 text-sm text-white/35"
        >
          Since {formatDate(FIRST_COMMIT)} · snapshot as of {formatDate(GENERATED_AT)}
        </motion.p>

        {/* STATS */}
        <motion.dl
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.32, ease: EASE }}
          className="mt-10 grid grid-cols-3 gap-4 border-y border-white/10 py-6"
        >
          {[
            { value: TOTAL_COMMITS, label: 'commits' },
            { value: NEW_COUNT, label: 'things shipped' },
            { value: ACTIVE_DAYS, label: 'active days' },
          ].map((stat) => (
            <div key={stat.label}>
              <dd className="flex items-baseline">
                <AnimatedCounter
                  value={stat.value}
                  className="font-display text-4xl font-bold leading-none text-white sm:text-5xl"
                />
              </dd>
              <dt className="mt-2 text-xs uppercase tracking-[0.16em] text-white/40">{stat.label}</dt>
            </div>
          ))}
        </motion.dl>
      </header>

      {/* FILTERS */}
      <div className="mx-auto w-full max-w-3xl px-6">
        <div className="flex flex-wrap gap-2">
          {FILTERS.map((f) => {
            const on = active === f.key
            return (
              <button
                key={f.key}
                type="button"
                onClick={() => setActive(f.key)}
                aria-pressed={on}
                className={`relative rounded-full px-4 py-1.5 text-sm font-semibold transition-colors ${
                  on ? 'text-black' : 'text-white/55 hover:text-white'
                }`}
              >
                {on && (
                  <motion.span
                    layoutId="logFilterPill"
                    className="absolute inset-0 -z-10 rounded-full bg-[#DCF87C]"
                    transition={{ type: 'spring', stiffness: 400, damping: 32 }}
                  />
                )}
                {f.label}
              </button>
            )
          })}
        </div>
      </div>

      {/* TIMELINE */}
      <section className="mx-auto w-full max-w-3xl px-6 pb-16 pt-10">
        <motion.div layout={!reduce} className="relative">
          {/* Vertical rail the day markers sit on. */}
          <span aria-hidden className="absolute bottom-2 left-[7px] top-2 w-px bg-white/10" />

          <AnimatePresence mode="popLayout" initial={false}>
            {groups.map((group) => (
              <motion.div
                key={group.date}
                layout={reduce ? false : 'position'}
                initial={reduce ? false : { opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={reduce ? undefined : { opacity: 0 }}
                transition={{ duration: 0.4, ease: EASE }}
                className="relative mb-8 pl-8"
              >
                {/* Day marker */}
                <span
                  aria-hidden
                  className="absolute left-0 top-1 h-3.5 w-3.5 rounded-full border-2 border-[#0a0a0a] bg-white/70 ring-1 ring-white/15"
                />
                <h2 className="font-display text-lg font-bold tracking-tight text-white/90">
                  {formatDay(group.date)}
                  <span className="ml-2 text-sm font-normal text-white/30">
                    {group.entries.length} {group.entries.length === 1 ? 'commit' : 'commits'}
                  </span>
                </h2>

                <div className="mt-2 -ml-3">
                  {group.entries.map((entry) => (
                    <CommitRow key={entry.hash} entry={entry} reduce={reduce} />
                  ))}
                </div>
              </motion.div>
            ))}
          </AnimatePresence>
        </motion.div>

        {filtered.length === 0 && (
          <p className="pl-8 text-white/40">Nothing in this slice yet.</p>
        )}
      </section>

      {/* CTA */}
      <section className="mx-auto w-full max-w-3xl px-6 pb-28 pt-4">
        <Reveal>
          <div className="rounded-3xl border border-white/10 bg-white/[0.02] p-8 text-center sm:p-12">
            <h2 className="font-display text-3xl font-bold tracking-tight sm:text-4xl">The whole thing is public.</h2>
            <p className="mx-auto mt-4 max-w-md leading-relaxed text-white/55">
              Every commit above links to its diff. Read the source, watch it grow, or clone it and make it yours.
            </p>
            <div className="mt-8 flex flex-wrap justify-center gap-3">
              <MagneticButton
                href={REPO_URL}
                className="rounded-full bg-[#DCF87C] px-7 py-3.5 text-base font-semibold text-black"
              >
                View the repo
              </MagneticButton>
              <Link
                to="/colophon"
                className="rounded-full border border-white/15 px-7 py-3.5 text-base font-semibold text-white transition-colors hover:bg-white/[0.06]"
              >
                How it is made
              </Link>
            </div>
          </div>
        </Reveal>
      </section>
    </>
  )
}
