// AUTO-GENERATED by scripts/generate-buildlog.mjs — do not edit by hand.
// A committed snapshot of this repo's real git history, powering /log.
// Regenerate with: node scripts/generate-buildlog.mjs

export type BuildKind = 'new' | 'refine' | 'docs'

export interface BuildEntry {
  hash: string
  date: string
  subject: string
  kind: BuildKind
}

/** Date (YYYY-MM-DD) of the latest commit in this snapshot. */
export const GENERATED_AT = '2026-07-12'

/** Date of the very first commit — the day the site began. */
export const FIRST_COMMIT = '2026-07-09'

/** Total commits across the whole history. */
export const TOTAL_COMMITS = 50

/** Distinct calendar days with at least one commit. */
export const ACTIVE_DAYS = 4

/** How many commits introduced something new ("Add …"), whole history. */
export const NEW_COUNT = 10

/** The most recent 60 commits, newest first. */
export const BUILD_LOG: readonly BuildEntry[] = [
  { hash: '93ba888', date: '2026-07-12', subject: 'HANDOFF: document Globe and its Contact + Playground integrations', kind: 'docs' },
  { hash: '1b7a782', date: '2026-07-12', subject: 'Colophon: bump hand-built component count to 73 for Globe', kind: 'refine' },
  { hash: '67dbd59', date: '2026-07-12', subject: 'Playground: add the rotating globe beside the tag sphere in Navigation & controls', kind: 'refine' },
  { hash: '45eb93a', date: '2026-07-12', subject: 'Contact: give the availability card a live globe that turns Berlin into view', kind: 'refine' },
  { hash: '2d86f22', date: '2026-07-12', subject: 'Add Globe: a dotted, drag-to-spin world with live location markers', kind: 'new' },
  { hash: 'a414220', date: '2026-07-12', subject: 'Colophon: bump component count to 72; document TagSphere in HANDOFF', kind: 'refine' },
  { hash: '3dd0966', date: '2026-07-12', subject: 'Playground: add the Tag sphere to Navigation & controls, beside the gravity bin', kind: 'refine' },
  { hash: 'e2db3f3', date: '2026-07-12', subject: 'Home: make the Toolkit skills a spin-to-explore 3D sphere over the marquee', kind: 'refine' },
  { hash: '9deddad', date: '2026-07-12', subject: 'Add TagSphere: a 3D word sphere that auto-spins and can be grabbed and flung', kind: 'new' },
  { hash: 'a69208a', date: '2026-07-11', subject: 'HANDOFF: document FlipCard, the useFinePointer hook extraction, and their integrations', kind: 'docs' },
  { hash: '76e1409', date: '2026-07-11', subject: 'Colophon: bump hand-built component count to 71 for FlipCard', kind: 'refine' },
  { hash: '59c4a0c', date: '2026-07-11', subject: 'Home: turn the About teaser facets into flip cards, foregrounding the person over any one project', kind: 'refine' },
  { hash: '1d46d05', date: '2026-07-11', subject: 'Playground: add the Flip card to Cards & surfaces', kind: 'refine' },
  { hash: '083dd42', date: '2026-07-11', subject: 'Add FlipCard: a real 3D rotateY flip with mid-turn sheen and depth dip', kind: 'new' },
  { hash: '70259a8', date: '2026-07-11', subject: 'Extract useFinePointer into a shared hook (used by SpotlightReveal)', kind: 'refine' },
  { hash: 'cad0833', date: '2026-07-11', subject: 'HANDOFF: document InfiniteScroll, its fling physics, and the inline-copies gotcha', kind: 'docs' },
  { hash: 'd8a2d03', date: '2026-07-11', subject: 'InfiniteScroll: inline the two copies so measuring never remounts and freezes the drift', kind: 'refine' },
  { hash: '8c999f1', date: '2026-07-11', subject: 'Colophon: bump hand-built component count to 70 for InfiniteScroll', kind: 'refine' },
  { hash: '3126f34', date: '2026-07-11', subject: 'Playground: add the infinite fling column to Navigation & controls, two columns drifting opposite ways', kind: 'refine' },
  { hash: '0488bed', date: '2026-07-11', subject: 'Add InfiniteScroll: a vertical looping column you can fling, with decaying momentum', kind: 'new' },
  { hash: '1c353c9', date: '2026-07-11', subject: 'HANDOFF: document the /range page and its navigation integrations', kind: 'docs' },
  { hash: '492a4cd', date: '2026-07-11', subject: 'Colophon: bump page count to 16 for /range', kind: 'refine' },
  { hash: '63af481', date: '2026-07-11', subject: 'Home: link the Range section and Explore menu into the new /range page', kind: 'refine' },
  { hash: '17b7e91', date: '2026-07-11', subject: 'Wire /range into the command palette and the g-d go-chord', kind: 'refine' },
  { hash: '8b6d114', date: '2026-07-11', subject: 'Nav: make Range a primary link, foregrounding breadth over any one project', kind: 'refine' },
  { hash: 'b21cfc0', date: '2026-07-11', subject: 'Add /range: an index/detail explorer for the disciplines Arseniy works across', kind: 'new' },
  { hash: 'b708457', date: '2026-07-10', subject: 'HANDOFF: document the /craft \'On motion\' page and its navigation integrations', kind: 'docs' },
  { hash: 'ccc013d', date: '2026-07-10', subject: 'Cross-link /craft from About, the Home Explore menu, and bump Colophon page count to 15', kind: 'refine' },
  { hash: '4be83e4', date: '2026-07-10', subject: 'Wire /craft into navigation: g-m chord, command palette, footer, and mobile menu', kind: 'refine' },
  { hash: '400c6b6', date: '2026-07-10', subject: 'Add /craft: an interactive \'On motion\' page where four craft beliefs are playable, not stated', kind: 'new' },
  { hash: '9ce7e99', date: '2026-07-10', subject: 'HANDOFF: document ASCIIText and its Colophon + Playground integrations', kind: 'docs' },
  { hash: '17a0935', date: '2026-07-10', subject: 'Colophon: bump hand-built component count to 69 for ASCIIText', kind: 'refine' },
  { hash: 'e587c1e', date: '2026-07-10', subject: 'Playground: add the live ASCII type field to the Type & text band', kind: 'refine' },
  { hash: 'cf18ddf', date: '2026-07-10', subject: 'Colophon: sign off with the name rendered as a live ASCII field', kind: 'refine' },
  { hash: '11b2386', date: '2026-07-10', subject: 'Add ASCIIText: a word rendered as a live, cursor-lit ASCII field', kind: 'new' },
  { hash: 'ab88a1b', date: '2026-07-10', subject: 'HANDOFF: document Stepper and its Colophon + Playground integrations', kind: 'docs' },
  { hash: 'e74babe', date: '2026-07-10', subject: 'Colophon: bump hand-built component count to 68 for Stepper', kind: 'refine' },
  { hash: '4c689b8', date: '2026-07-10', subject: 'Playground: add the Stepper to Navigation & controls with a four-way demo', kind: 'refine' },
  { hash: 'a552a17', date: '2026-07-10', subject: 'Colophon: add a \'How a change ships\' Stepper walking the real build pipeline', kind: 'refine' },
  { hash: '0fcdad6', date: '2026-07-10', subject: 'Stepper: accept a readonly steps list so const data can drive it', kind: 'refine' },
  { hash: '72e03b7', date: '2026-07-10', subject: 'Add Stepper: an accessible, animated step-through with a sweeping lime rail', kind: 'new' },
  { hash: '15a076c', date: '2026-07-09', subject: 'HANDOFF: document ChromaGrid and its NotFound + Playground integrations', kind: 'docs' },
  { hash: '147542a', date: '2026-07-09', subject: 'Colophon: bump hand-built component count to 67 for ChromaGrid', kind: 'refine' },
  { hash: 'd09ba5f', date: '2026-07-09', subject: 'NotFound: light the way out with a ChromaGrid of honest landing spots', kind: 'refine' },
  { hash: 'cfb33e0', date: '2026-07-09', subject: 'Playground: add the ChromaGrid torch-in-the-dark experiment to Cards & surfaces', kind: 'refine' },
  { hash: 'fc77c6f', date: '2026-07-09', subject: 'Add ChromaGrid: a torch-in-the-dark card grid that lights cards under the cursor', kind: 'new' },
  { hash: '60b14dc', date: '2026-07-09', subject: 'HANDOFF: document route code-splitting, the Suspense boundary, and RouteFallback', kind: 'docs' },
  { hash: '456b869', date: '2026-07-09', subject: 'App: code-split every route into its own chunk, keeping Home eager', kind: 'refine' },
  { hash: '0917797', date: '2026-07-09', subject: 'Layout: wrap the route outlet in a Suspense boundary for lazy pages', kind: 'refine' },
  { hash: '2273b89', date: '2026-07-09', subject: 'Add RouteFallback: a calm branded loader for streaming route chunks', kind: 'new' },
]
